# Data Preparation and Sampling

![stage1](https://camo.githubusercontent.com/590a463dcb825375473c9fd366013e86204589d68be0bd0207d43b158ba10558/68747470733a2f2f73656261737469616e72617363686b612e636f6d2f696d616765732f4c4c4d732d66726f6d2d736372617463682d696d616765732f636830325f636f6d707265737365642f30312e776562703f74696d657374616d703d31)

In [ ]:
# Import libraries
import re

In [2]:
# Connect to Google Drive
# from google.colab import drive
# drive.mount('/content/drive')


In [3]:
with open("../_data/the-verdict.txt", "r", encoding="utf-8") as f:
  raw_text = f.read()

print("Total number of character:", len(raw_text))
print(raw_text[:99])

Total number of character: 20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


### 1. Tokenization

In [4]:
# Split the sentence to words (or tokens)
# In the splitting process, remove space, commas, and periods.
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
print(preprocessed[:30])
print(len(preprocessed))

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']
4690


**Converting tokens into token IDs**
![tokenids](https://camo.githubusercontent.com/bf01ba4b1b924633325cda845feac84ae1a3f154db5098f5d70e90470ff4484e/68747470733a2f2f73656261737469616e72617363686b612e636f6d2f696d616765732f4c4c4d732d66726f6d2d736372617463682d696d616765732f636830325f636f6d707265737365642f30362e77656270)

### 2. Create Token Ids (Integers) + Build Vocabulary

I am building a Vocabulary Dictionary and Sorting it Alphabetical Order. This is something that I would be using to give a numarical value to my tokens.

In [5]:
# From these tokens, we can now build a vocabulary that consists of all the unique tokens
all_words = sorted(set(preprocessed))
vocab_size = len(all_words)

print(vocab_size)

vocab = {token:integer for integer,token in enumerate(all_words)}

# Below are the first 50 entries in this vocabulary:
for i, item in enumerate(vocab.items()):
    print(item)
    if i >= 50:
        break

1130
('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)


Below, we illustrate the tokenization of a short sample text using a small vocabulary:
![token vocab](https://camo.githubusercontent.com/8955d3aea45dc06f156d0579f7f3302c27b6635e649c301dbab33427b2d8d2a8/68747470733a2f2f73656261737469616e72617363686b612e636f6d2f696d616765732f4c4c4d732d66726f6d2d736372617463682d696d616765732f636830325f636f6d707265737365642f30372e776562703f313233)

**Putting it now all together into a tokenizer class**
- Encoding the input text to Integers
- Decoding the integers into text.

In [6]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = {i:s for s,i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)

        preprocessed = [
            item.strip() for item in preprocessed if item.strip()
        ]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

- The encode function turns text into token IDs
- The decode function turns token IDs back into text

![tokenizer](https://camo.githubusercontent.com/b324e29fe9d3d4191a9200d6a08983eef4d3f835cff85ce1ee4aceb47117891a/68747470733a2f2f73656261737469616e72617363686b612e636f6d2f696d616765732f4c4c4d732d66726f6d2d736372617463682d696d616765732f636830325f636f6d707265737365642f30382e776562703f313233)


In [7]:
# We can use the tokenizer to encode (that is, tokenize) texts into integers. These integers can then be embedded (later) as input of/for the LLM
tokenizer = SimpleTokenizerV1(vocab)

text = """"It's the last he painted, you know,"
           Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
print("Encoded Tokens: ")
print(ids)
print("\n")

# We can decode the integers back into text
print("Encoded Tokens back to Text: ")
print(tokenizer.decode(ids))
print("\n")


Encoded Tokens: 
[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]


Encoded Tokens back to Text: 
" It' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.




**Adding special context tokens**

It's useful to add some "special" tokens for unknown words and to denote the end of a text

![special tokens](https://camo.githubusercontent.com/11a0a59ffbb8eb8e6a90eb4ea7706e4be0d7ed9b53cadd0d31f676af267866c0/68747470733a2f2f73656261737469616e72617363686b612e636f6d2f696d616765732f4c4c4d732d66726f6d2d736372617463682d696d616765732f636830325f636f6d707265737365642f30392e776562703f313233)

#### Special Tokens in Tokenizers

Some tokenizers use **special tokens** to help the LLM with additional context.

##### Common Special Tokens

- **[BOS]** (*Beginning of Sequence*) — Marks the beginning of text.  
- **[EOS]** (*End of Sequence*) — Marks where the text ends.  
  - This is usually used to concatenate multiple unrelated texts (e.g., two different Wikipedia articles or books).  
- **[PAD]** (*Padding*) — Used when training LLMs with a batch size greater than 1.  
  - Since texts may have different lengths, the padding token ensures that all sequences in a batch are of equal length by padding the shorter ones.  
- **[UNK]** (*Unknown*) — Represents words that are not included in the vocabulary.  

---

##### GPT-2 and Special Tokens

- **GPT-2** simplifies token usage — it **does not use** `[BOS]`, `[EOS]`, `[PAD]`, or `[UNK]`.  
- Instead, GPT-2 uses a single token:  
  - **`<|endoftext|>`** — analogous to the `[EOS]` token.  
- GPT-2 also uses `<|endoftext|>` for padding since, during training, **attention masks** ensure that padded tokens are ignored.  
- **No `<UNK>` token** — GPT-2 employs a **Byte Pair Encoding (BPE)** tokenizer, which breaks words into subword units instead of marking them as unknown.  

---

##### Usage Between Texts

We use the **`<|endoftext|>`** token between two independent sources of text to separate them cleanly.

![special context](https://camo.githubusercontent.com/1e57f90c79530539cb8e6c14233f52b88857f7f89afcd75fe0381fae7cf64ccd/68747470733a2f2f73656261737469616e72617363686b612e636f6d2f696d616765732f4c4c4d732d66726f6d2d736372617463682d696d616765732f636830325f636f6d707265737365642f31302e77656270)

In [8]:
# Let's what happen we encode a text which has words not present in the vocab we have built above.
## The vocab we built above does not have the word "Hello". So, encoding a text with this word should raise an error.
tokenizer = SimpleTokenizerV1(vocab)

text = "Hello, do you like tea. Is this-- a test?"

tokenizer.encode(text)

KeyError: 'Hello'

In [ ]:
# The above produces an error because the word "Hello" is not contained in the vocabulary
# To deal with such cases, we can add special tokens like "<|unk|>" to the vocabulary to represent unknown words
# Since we are already extending the vocabulary, let's add another token called "<|endoftext|>"
# which is used in GPT-2 training to denote the end of a text (and it's also used between concatenated text,
# like if our training datasets consists of multiple articles, books, etc.)

all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

vocab = {token:integer for integer,token in enumerate(all_tokens)}
len(vocab.items())

1132

In [ ]:
# Now let's update the tokenizer class SimpleTokenizerV2 to handle for unknown words
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = { i:s for s,i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        preprocessed = [
            item if item in self.str_to_int
            else "<|unk|>" for item in preprocessed
        ]

        ids = [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        # Replace spaces before the specified punctuations
        text = re.sub(r'\s+([,.:;?!"()\'])', r'\1', text)
        return text

In [ ]:
tokenizer = SimpleTokenizerV2(vocab)

text1 = "Hello, do you like tea. Is this-- a test?"
text2 = "In the sunlit terraces of the palace."

text = " <|endoftext|> ".join((text1, text2))

print(text)
print("\n")

print("Encoded: ")
ids = tokenizer.encode(text)
print(ids)
print("\n")

print("Decoded: ")
print(tokenizer.decode(ids))
print("\n")



Hello, do you like tea. Is this-- a test? <|endoftext|> In the sunlit terraces of the palace.


Encoded: 
[1131, 5, 355, 1126, 628, 975, 7, 1131, 999, 6, 115, 1131, 10, 1130, 55, 988, 956, 984, 722, 988, 1131, 7]


Decoded: 
<|unk|>, do you like tea. <|unk|> this -- a <|unk|>? <|endoftext|> In the sunlit terraces of the <|unk|>.




### 3. BytePair encoding

In Section-2 above, we learned about how Token-ID encoding is done. Here, we will learn the practical way using BPE.

- GPT-2 used BytePair encoding (BPE) as its tokenizer. (Splits words into subword units based on frequency.)

- It allows the model to break down words that aren't in its predefined vocabulary into smaller subword units or even individual characters, enabling it to handle out-of-vocabulary words

- For instance, if GPT-2's vocabulary doesn't have the word "unfamiliarword," it might tokenize it as ["unfam", "iliar", "word"] or some other subword breakdown, depending on its trained BPE merges

- The original BPE tokenizer can be found here: https://github.com/openai/gpt-2/blob/master/src/encoder.py

- In this chapter, we are using the BPE tokenizer from OpenAI's open-source tiktoken library, which implements its core algorithms in Rust to improve computational performance

In [ ]:
import importlib
import tiktoken # OpenAI's tokenizer library

print("tiktoken version:", importlib.metadata.version("tiktoken"))

tiktoken version: 0.12.0


In [ ]:
tokenizer = tiktoken.get_encoding("gpt2")

In [ ]:
text = (
    "Hello, do you like tea? <|endoftext|> In the sunlit terraces"
     "of someunknownPlace."
)

integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})

print(integers)
print("\n")

strings = tokenizer.decode(integers)

print(strings)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]


Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.


BPE tokenizers break down unknown words into subwords and individual characters:

![](https://camo.githubusercontent.com/5938dff392e5cb7404d2636e4d7157fceb4c36ecf57a2173001bd3edf22234da/68747470733a2f2f73656261737469616e72617363686b612e636f6d2f696d616765732f4c4c4d732d66726f6d2d736372617463682d696d616765732f636830325f636f6d707265737365642f31312e77656270)

### 4. Sampling: Data sampling with a sliding window

We train LLMs to generate one word at a time, so we want to prepare the training data accordingly where the next word in a sequence represents the target to predict:

![datawithslidingwindow](https://camo.githubusercontent.com/b6245f4e6c64740c06f71ddd30d6495342b37315f0fd3556a0dc511be009a61f/68747470733a2f2f73656261737469616e72617363686b612e636f6d2f696d616765732f4c4c4d732d66726f6d2d736372617463682d696d616765732f636830325f636f6d707265737365642f31322e77656270)

In [ ]:
import torch
print("PyTorch version:", torch.__version__)

PyTorch version: 2.9.0+cu128


We use a sliding window approach, changing the position by +1:
![](https://camo.githubusercontent.com/9c738e75095f70d3dc4f6b3630008dd67607b5fa92e3bf776b0ed2cbb68db299/68747470733a2f2f73656261737469616e72617363686b612e636f6d2f696d616765732f4c4c4d732d66726f6d2d736372617463682d696d616765732f636830325f636f6d707265737365642f31332e776562703f313233)

Create dataset and dataloader that extract chunks from the input text dataset.

When training a model like GPT, you usually have a very long text, but the model can only process a limited number of tokens at a time (for example, 1024 or 2048). So we must split the long text into manageable chunks (tensors).

That’s where max_length and stride come in.
**max_length**: defines how many tokens go into each training example (tensor).

For example, if:
 - max_length = 10
 - your text has 25 tokens → [t1, t2, …, t25]
Then the dataset will split it like:
```
[ t1 … t10 ]
[ t11 … t20 ]
[ t21 … t25 ]

```
Each of these becomes one training example (input tensor).

**stride**: Controls how much overlap there is between consecutive training chunks.

If you use a stride smaller than max_length, you slide the window by fewer tokens, so the next chunk reuses some context from the previous one.

```
Suppose:
max_length = 10
stride = 5
and your tokens are [t1, t2, t3, …, t25].

Then your dataset chunks will be:
Chunk 1: t1  to t10
Chunk 2: t6  to t15
Chunk 3: t11 to t20
Chunk 4: t16 to t25
```

**Notice:**
- The input text is converted into tokens (array of tokens)
- Then, the complete token array is split into small arrays/chuncks/sampples (each array of max_length size). 
- stride is used to have an overlap of tokens between each consecutive chunks.

**batch_size**: The number of samples (or tensors) processed in one batch (i.e one forward and backward pass of the model).

**context window**: Is the maximum number of token a model can process. This is = max_length..
E.g. GPT-3.5 token length is 16,384. It is the maximum number of token the model can process per batch.

**stride**: stride controls how much the sliding window moves forward when chunking the tokenized text into overlapping sequences.

Examples

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

**With max_length=10 and stride=1** --> overlap of 9 (10-1) tokens

Window 1: [ 0  1  2  3  4  5  6  7  8  9]
Window 2: [ 1  2  3  4  5  6  7  8  9 10]
Window 3: [ 2  3  4  5  6  7  8  9 10 11]
Window 4: [ 3  4  5  6  7  8  9 10 11 12]
...

**With max_length=10 and stride=5**--> overlap of 5 (10-5) tokens

Window 1: [ 0  1  2  3  4  5  6  7  8  9]
Window 2: [ 5  6  7  8  9 10 11 12 13 14]
Window 3: [10 11 12 13 14 15 16 17 18 19]

**With max_length=10 and stride=10**--> overlap of 0 (10-0) tokens --> no overlap

Window 1: [ 0  1  2  3  4  5  6  7  8  9]
Window 2: [10 11 12 13 14 15 16 17 18 19]





The **torch.utils.data.DataLoader** is one of PyTorch’s most powerful utilities — it’s not just a simple loop helper, it’s an engine that manages how your data flows into the model efficiently.

The **DataLoader** wraps a Dataset and handles batching, shuffling, sampling, parallel loading, memory pinning, and collation.

dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)
print("\n")

Understand the output here.

[
    tensor([[  40,  367, 2885, 1464],  --> this is the input tensor
        [ 367, 2885, 1464, 1807]]),    --> the tensor has 2 array of size 4. This is because batch_size=2, max_length=4
        
    tensor([[ 367, 2885, 1464, 1807],  --> this is the target or exepected output tensor
        [2885, 1464, 1807, 3619]])
]

**Note**

- max_length is also called sequence length or context window of the model. It is nothing but the TOKEN SIZE of the model. 
- batch_size = number of sequences processed in parallel
- embedding_dimension = is the dimension of the vector used by the model to store the tokens. It is internal to model.


In [ ]:
import importlib
import tiktoken
import torch
from torch.utils.data import Dataset, DataLoader

tokenizer = tiktoken.get_encoding("gpt2")

class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})
        assert len(token_ids) > max_length, "Number of tokenized inputs must at least be equal to max_length+1"

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]

def create_dataloader_v1(txt, batch_size=4, max_length=256,
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    ## max_length --> how many tokens will be placed in each tensor
    ## stride --> ??
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,   # number of samples/chunks per batch
        shuffle=shuffle,         # whether to shuffle the data at every epoch
        drop_last=drop_last,     # true means that the last batch is dropped if it's smaller than batch_size
        num_workers=num_workers  # >0 is used for parallel data loading
    )

    return dataloader

In [ ]:
batch_size=2
max_length=4
stride=1

with open("../_data/the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

dataloader = create_dataloader_v1(
    raw_text, batch_size=batch_size, max_length=max_length, stride=stride, shuffle=False
)

data_iter = iter(dataloader)
print("First Batch:")
input1, target1 = next(data_iter)
print("Input Tensor:", input1)
print("Decoded Tensor:", tokenizer.decode(input1[0].tolist()))
print("Decoded Tensor:", tokenizer.decode(input1[1].tolist()))
print("\n")
print("Expected Output Tensor:", target1)
print("Decoded Tensor:", tokenizer.decode(target1[0].tolist()))
print("Decoded Tensor:", tokenizer.decode(target1[1].tolist()))
print("\n")

print("Second Batch:")
input2, target2 = next(data_iter)
print("Input Tensor:", input2)
print("Decoded Tensor:", tokenizer.decode(input2[0].tolist()))
print("Decoded Tensor:", tokenizer.decode(input2[1].tolist()))
print("\n")
print("Expected Output Tensor:", target2)
print("Decoded Tensor:", tokenizer.decode(target2[0].tolist()))
print("Decoded Tensor:", tokenizer.decode(target2[1].tolist()))
print("\n")

First Batch:
Input Tensor: tensor([[  40,  367, 2885, 1464],
        [ 367, 2885, 1464, 1807]])
Decoded Tensor: I HAD always
Decoded Tensor:  HAD always thought


Expected Output Tensor: tensor([[ 367, 2885, 1464, 1807],
        [2885, 1464, 1807, 3619]])
Decoded Tensor:  HAD always thought
Decoded Tensor: AD always thought Jack


Second Batch:
Input Tensor: tensor([[2885, 1464, 1807, 3619],
        [1464, 1807, 3619,  402]])
Decoded Tensor: AD always thought Jack
Decoded Tensor:  always thought Jack G


Expected Output Tensor: tensor([[1464, 1807, 3619,  402],
        [1807, 3619,  402,  271]])
Decoded Tensor:  always thought Jack G
Decoded Tensor:  thought Jack Gis




### 5. Token Embeddings

let us embed the tokens into a continuous vector representation using an embedding layer.
Usually, these embedding layers are part of the LLM itself and are updated (trained) during model training.

![Embedding](https://camo.githubusercontent.com/cad0f97a119e344cc132e00a75f4b29baa23bae26eb9efa31fcb2ff44bc8b1cc/68747470733a2f2f73656261737469616e72617363686b612e636f6d2f696d616765732f4c4c4d732d66726f6d2d736372617463682d696d616765732f636830325f636f6d707265737365642f31352e77656270)


In [ ]:
vocab_size = tokenizer.n_vocab
embedding_dim = 128
embedding_layer = torch.nn.Embedding(
    num_embeddings=vocab_size,      # size of the vocabulary. That is, total number of unique tokens
    embedding_dim=embedding_dim     # dimension of the embedding vector for each token
)   

# Example token IDs
token_ids = torch.tensor([15496, 11, 703, 389])
token_ids.shape

# Get embeddings
embeddings = embedding_layer(token_ids)
print(embeddings.shape)
print(embeddings)

torch.Size([4, 128])
tensor([[ 0.4919,  0.5836, -0.4788, -0.5867, -0.4326,  0.0219, -0.7631, -0.3604,
          0.3033,  0.7788,  0.5383, -0.5911,  1.1915,  2.0760,  0.4669,  0.2700,
          0.7211,  1.2787, -1.0647,  0.2526,  1.0437,  0.7300, -0.3827,  0.3834,
          0.1768, -0.8270, -1.2523, -0.8677,  1.4941, -0.7357, -0.1139, -1.9525,
          0.8607, -0.0981,  0.0403, -0.6859,  1.7577, -0.3760,  0.4799,  1.3499,
         -0.1287, -0.8746, -0.0395,  0.4360,  0.7254, -1.3802, -0.2777, -0.7300,
          1.6153,  0.0424,  0.2142,  0.3498, -0.2399, -1.3444, -0.6124,  0.8006,
          0.9300, -1.1502,  0.2665,  1.5674,  0.4683,  0.7776,  0.3345,  0.4141,
         -0.0145, -1.5066, -1.3196,  0.8494, -0.9964,  0.5403,  0.3468,  1.5073,
         -1.4258, -0.1474, -0.5213,  0.8206,  1.6428,  1.0459,  0.1935,  2.2498,
         -0.9397,  0.9861,  0.4863, -0.5298, -0.7505,  0.9231, -0.3530, -0.1587,
         -0.2162, -0.3538, -0.4384, -1.0969,  1.1176, -0.3549,  1.1794,  0.7936,
       

In [ ]:
print(embedding_layer(input1))
print(embedding_layer.weight)

tensor([[[ 0.8572, -0.0949, -0.0674,  ...,  1.6262,  0.4949, -0.9278],
         [-0.2643,  0.3225,  0.7887,  ...,  1.0567,  0.7091, -0.5430],
         [ 0.0850, -0.9124, -0.6547,  ..., -1.0258, -0.3896, -1.1745],
         [-1.3894,  0.3758,  0.1477,  ..., -0.7676, -1.3244, -0.3334]],

        [[-0.2643,  0.3225,  0.7887,  ...,  1.0567,  0.7091, -0.5430],
         [ 0.0850, -0.9124, -0.6547,  ..., -1.0258, -0.3896, -1.1745],
         [-1.3894,  0.3758,  0.1477,  ..., -0.7676, -1.3244, -0.3334],
         [ 0.5022,  1.2511, -0.2445,  ...,  0.2588, -0.2768,  0.2597]]],
       grad_fn=<EmbeddingBackward0>)
Parameter containing:
tensor([[ 1.7934,  1.7447, -0.6078,  ..., -0.4965,  1.1797,  0.6800],
        [-0.2222, -0.6934, -1.4048,  ...,  0.6152,  0.6212, -0.5946],
        [-0.3884, -0.4185, -1.4137,  ..., -0.6162, -0.4294,  0.9796],
        ...,
        [-0.2919, -0.4982, -0.0549,  ..., -0.9170, -1.1971,  0.7040],
        [-1.0929,  0.2177,  0.4344,  ...,  0.1323,  0.5005,  0.8721],
      

### 6. Add Positional Encoding

1. The Embedding layer above converts IDs into identical vector representations regardless of where they are located in the input sequence.

![Embedding](https://camo.githubusercontent.com/2659e7bc3eed30da2e6a0e6adc3143d6240c2759e5315481b21877eb12de47e1/68747470733a2f2f73656261737469616e72617363686b612e636f6d2f696d616765732f4c4c4d732d66726f6d2d736372617463682d696d616765732f636830325f636f6d707265737365642f31372e77656270)


2. Positional embeddings are combined with the token embedding vector to form the FINAL input embeddings for a large language model processing.

![Positional Encoding](https://camo.githubusercontent.com/e53fdceda6a07218acfe115d81dc930241569fbbcd5c3e533856dee1959a8a93/68747470733a2f2f73656261737469616e72617363686b612e636f6d2f696d616765732f4c4c4d732d66726f6d2d736372617463682d696d616765732f636830325f636f6d707265737365642f31382e77656270)



In [ ]:
# Positional Encoding
# Positional encoding is a key concept in transformer-based models (like GPT, BERT, etc.) 
# because, unlike RNNs, transformers don’t have a built-in notion of word order.
# GPT-2 uses absolute position embeddings, so we just create another embedding layer:

vocab_size = max_length  # maximum position index
embedding_dim = 128
positional_embedding_layer = torch.nn.Embedding(
    num_embeddings=vocab_size,      # size of the vocabulary. That is, total number of unique tokens
    embedding_dim=embedding_dim     # dimension of the embedding vector for each token
)   

pos_embeddings = positional_embedding_layer(torch.arange(max_length))

# Add the positional encoding to the token embeddings
input_embeddings = embedding_layer(input1) + pos_embeddings
print(input_embeddings.shape)
print(input_embeddings)



torch.Size([2, 4, 128])
tensor([[[-1.3211,  0.6931,  0.7966,  ...,  1.7436,  1.3719, -0.4867],
         [ 0.1186,  1.4148, -0.7753,  ...,  0.9467, -0.9491, -0.0198],
         [ 0.7639, -0.6555, -0.5174,  ..., -0.3773,  0.6467, -2.9255],
         [-0.5118,  2.2718, -0.8102,  ..., -1.5434, -0.1387, -1.1988]],

        [[-2.4426,  1.1104,  1.6527,  ...,  1.1740,  1.5861, -0.1019],
         [ 0.4679,  0.1800, -2.2187,  ..., -1.1358, -2.0478, -0.6512],
         [-0.7105,  0.6326,  0.2850,  ..., -0.1191, -0.2880, -2.0844],
         [ 1.3798,  3.1471, -1.2025,  ..., -0.5170,  0.9089, -0.6057]]],
       grad_fn=<AddBackward0>)
Parameter containing:
tensor([[-2.1783,  0.7880,  0.8640,  0.0499, -0.4130, -0.2857,  0.5581,  0.2588,
         -0.8587,  1.8153, -0.5469, -1.2586,  0.4525, -0.0455,  0.9426, -0.7919,
          1.0008,  0.5892, -0.2208, -0.6678,  1.6323, -0.8804,  0.0456,  0.6102,
         -0.5970,  0.9962,  0.1780, -0.8567,  0.9069,  0.7035, -0.8602, -0.8870,
         -0.1566,  0.7834, 

![flow](https://camo.githubusercontent.com/730badacd85e476130cab5a98990d3c616b4333921096c576c31a50e7c0ca627/68747470733a2f2f73656261737469616e72617363686b612e636f6d2f696d616765732f4c4c4d732d66726f6d2d736372617463682d696d616765732f636830325f636f6d707265737365642f31392e77656270)